# Generated by Django 4.0.5 on 2023-04-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='Unknown')),
                ('burgers', models.JSONField()),
                ('appetizers', models.CharField(default='None', max_length=20)),
                ('drinks', models.CharField(default='None', max_length=20)),
                ('paymeth', models.CharField(default='Unknown', max_length=10)),
                ('total', models.FloatField()),
                ('timestamp', models.TimeField(auto_now=True)),
                ('datestamp', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burgers', models.JSONField()),
                ('appetizers', models.CharField(default='None', max_length=20)),
                ('drinks', models.CharField(default='None', max_length=20)),
                ('total', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
