# Generated by Django 4.0.5 on 2023-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orders_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.JSONField(default=dict),
        ),
    ]
